name: ci

on:
  schedule:
    - cron: "0 10 * * *" # everyday at 10am
  push:
    branches: main

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push debian
        uses: docker/build-push-action@v2
        with:
          context: ./0/debian
          file: ./0/debian/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            uuznn/waline:latest
            uuznn/waline:slim
            uuznn/waline:0-slim
            uuznn/waline:0
            ghcr.io/uuznn/waline:latest
            ghcr.io/uuznn/waline:slim
            ghcr.io/uuznn/waline:0-slim
            ghcr.io/uuznn/waline:0
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      - name: Build and push alpine
        uses: docker/build-push-action@v2
        with:
          context: ./0/alpine
          file: ./0/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            uuznn/waline:alpine
            uuznn/waline:0-alpine
            ghcr.io/uuznn/waline:alpine
            ghcr.io/uuznn/waline:0-alpine
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
